### ISSUE TITLE
2.2.2章节里中文版翻译错误

### ISSUE THREAD

**Issue by geduo44** [quanke/think-in-java#20]
2.2.2章节里，英文版是：
The “wrapper” classes for the primitive data types allow you to make a non-primitive object
on the heap to represent that primitive type. For example:
char c = ‘x’;
Character ch = new Character(c);
中文版看到的是：
主数据类型也拥有自己的“封装器”(wrapper)类。这意味着假如想让堆内一个非主要对象表示那个主类
型,就要使用对应的封装器。例如: 
char c = 'x'; 
Character C = new Character('c'); 

请注意最后一行，传入的参数是句柄c，而不是字符'c'。

英文版引自：https://github.com/DoingLee/Thinking-in-Java-4th-Edition

**Comment by geduo44** [comment]
Please check the pull request https://github.com/quanke/think-in-java/pull/21

**Comment by milla** [comment]
麻烦纠正一下“多形性”应为“多态性”

**Comment by quanke** [comment]
fix
